apiVersion: redhatcop.redhat.io/v1alpha1
kind: VaultSecret
metadata:
  name: bmh-secret
  namespace: worker2
spec:
  refreshPeriod: 1m0s
  vaultSecretDefinitions:
    - authentication:
        path: kubernetes
        role: bmc-secrets-reader
        serviceAccount:
          name: bmcsecret-service
      name: bmcsecretservice
      path: kv/global-secrets/bmc-secret/secret
    - authentication:
        path: kubernetes
        role: bmc-secrets-reader
        serviceAccount:
          name: bmcsecret-service
      name: bmcsecretservice
      path: kv/global-secrets/bmc-secret/secret
  output:
    name: worker2-bmh-secret
    stringData:
      username: '{{ .bmcsecretservice.username }}'
      password: '{{ .bmcsecretservice.password }}'
    type: Opaque
    labels:
      app: test-vault-config-operator
    annotations:
      refresh: every-minute
